package com.ridematefinder.sql;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Badges generated by hbm2java
 */
@Entity
@Table(name="badges"
    ,schema="public"
)
public class Badges  implements java.io.Serializable {


     private UUID id;
     private Pictures pictures;
     private String badgeDescription;
     private Set<Userbadges> userbadgeses = new HashSet<Userbadges>(0);

    public Badges() {
    }

	
    public Badges(UUID id) {
        this.id = id;
    }
    public Badges(UUID id, Pictures pictures, String badgeDescription, Set<Userbadges> userbadgeses) {
       this.id = id;
       this.pictures = pictures;
       this.badgeDescription = badgeDescription;
       this.userbadgeses = userbadgeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="badge_picture_id")
    public Pictures getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Pictures pictures) {
        this.pictures = pictures;
    }

    
    @Column(name="badge_description")
    public String getBadgeDescription() {
        return this.badgeDescription;
    }
    
    public void setBadgeDescription(String badgeDescription) {
        this.badgeDescription = badgeDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="badges")
    public Set<Userbadges> getUserbadgeses() {
        return this.userbadgeses;
    }
    
    public void setUserbadgeses(Set<Userbadges> userbadgeses) {
        this.userbadgeses = userbadgeses;
    }




}


