package com.ridematefinder.sql;


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name="car"
    ,schema="public"
)
public class Car  implements java.io.Serializable {


     private UUID id;
     private Pictures pictures;
     private User user;
     private String vin;
     private String model;
     private Integer year;
     private Integer numOfSeats;
     private Set<Opinioncar> opinioncars = new HashSet<Opinioncar>(0);
     private Set<Route> routes = new HashSet<Route>(0);


    public Car() {
    }

	
    public Car(UUID id) {
        this.id = id;
    }
    public Car(UUID id, Pictures pictures, User user, String vin, String model, Integer year, Integer numOfSeats, Set<Opinioncar> opinioncars, Set<Route> routes) {
       this.id = id;
       this.pictures = pictures;
       this.user = user;
       this.vin = vin;
       this.model = model;
       this.year = year;
       this.numOfSeats = numOfSeats;
       this.opinioncars = opinioncars;
       this.routes = routes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="car_picture_id")
    @JsonBackReference
    public Pictures getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Pictures pictures) {
        this.pictures = pictures;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", referencedColumnName = "driver_id")
@JsonBackReference
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="vin", length=255)
    public String getVin() {
        return this.vin;
    }
    
    public void setVin(String vin) {
        this.vin = vin;
    }

    
    @Column(name="model", length=255)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }


    @Column(name="num_of_seats")
    public Integer getNumOfSeats() {
        return this.numOfSeats;
    }
    
    public void setNumOfSeats(Integer numOfSeats) {
        this.numOfSeats = numOfSeats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="car")
    public Set<Opinioncar> getOpinioncars() {
        return this.opinioncars;
    }
    
    public void setOpinioncars(Set<Opinioncar> opinioncars) {
        this.opinioncars = opinioncars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="car")
@JsonManagedReference
    public Set<Route> getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Set<Route> routes) {
        this.routes = routes;
    }




}


