package com.ridematefinder.sql;
// Generated 9 kwi 2024, 11:51:05 by Hibernate Tools 6.4.4.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Driver generated by hbm2java
 */
@Entity
@Table(name="driver"
    ,schema="public"
)
public class Driver  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;

    public Driver() {
    }

	
    public Driver(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Driver(int id, String name, String description) {
       this.id = id;
       this.name = name;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


