package com.ridematefinder.sql;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;

/**
 * Opinionuser generated by hbm2java
 */
@Entity
@Table(name="opinionuser", schema="public")
public class Opinionuser  implements java.io.Serializable {


     private UUID id;
     private User userByUserIdReceiver;
     private User userByUserIdSetter;
     private String opinion;
     private Integer stars;

    public Opinionuser() {
    }

	
    public Opinionuser(UUID id) {
        this.id = id;
    }
    public Opinionuser(UUID id, User userByUserIdReceiver, User userByUserIdSetter, String opinion, Integer stars) {
       this.id = id;
       this.userByUserIdReceiver = userByUserIdReceiver;
       this.userByUserIdSetter = userByUserIdSetter;
       this.opinion = opinion;
       this.stars = stars;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_receiver")
    public User getUserByUserIdReceiver() {
        return this.userByUserIdReceiver;
    }
    
    public void setUserByUserIdReceiver(User userByUserIdReceiver) {
        this.userByUserIdReceiver = userByUserIdReceiver;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_setter")
    public User getUserByUserIdSetter() {
        return this.userByUserIdSetter;
    }
    
    public void setUserByUserIdSetter(User userByUserIdSetter) {
        this.userByUserIdSetter = userByUserIdSetter;
    }

    
    @Column(name="opinion")
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    
    @Column(name="stars")
    public Integer getStars() {
        return this.stars;
    }
    
    public void setStars(Integer stars) {
        this.stars = stars;
    }
}


