package com.ridematefinder.sql;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;

/**
 * Opinioncar generated by hbm2java
 */
@Entity
@Table(name="opinioncar", schema="public")
public class Opinioncar  implements java.io.Serializable {


     private UUID id;
     private Car car;
     private User user;
     private String opinion;
     private Integer stars;

    public Opinioncar() {
    }

	
    public Opinioncar(UUID id) {
        this.id = id;
    }
    public Opinioncar(UUID id, Car car, User user, String opinion, Integer stars) {
       this.id = id;
       this.car = car;
       this.user = user;
       this.opinion = opinion;
       this.stars = stars;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_id")
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_setter")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="opinion")
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    
    @Column(name="stars")
    public Integer getStars() {
        return this.stars;
    }
    
    public void setStars(Integer stars) {
        this.stars = stars;
    }

}


