package com.ridematefinder.sql;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;

/**
 * Paymentdata generated by hbm2java
 */
@Entity
@Table(name="paymentdata"
    ,schema="public"
)
public class Paymentdata  implements java.io.Serializable {


     private UUID id;
     private User user;
     private String bankAccount;

    public Paymentdata() {
    }

	
    public Paymentdata(UUID id, String bankAccount) {
        this.id = id;
        this.bankAccount = bankAccount;
    }
    public Paymentdata(UUID id, User user, String bankAccount) {
       this.id = id;
       this.user = user;
       this.bankAccount = bankAccount;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="bank_account", nullable=false, length=255)
    public String getBankAccount() {
        return this.bankAccount;
    }
    
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }




}


