package com.ridematefinder.sql;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import java.util.UUID;
import org.hibernate.annotations.GenericGenerator;

/**
 * Paymentdata generated by hbm2java
 */
@Entity
@Table(name="paymentdata"
    ,schema="public"
)
public class Paymentdata  implements java.io.Serializable {


     private UUID userId;
     private User user;
     private String bankAccount;

    public Paymentdata() {
    }

    public Paymentdata(User user, String bankAccount) {
       this.user = user;
       this.bankAccount = bankAccount;
    }
   
     @GenericGenerator(name="com.ridematefinder.sql.PaymentdataIdGenerator", strategy="foreign")@Id @GeneratedValue(generator="com.ridematefinder.sql.PaymentdataIdGenerator")

    
    @Column(name="user_id", unique=true, nullable=false)
    public UUID getUserId() {
        return this.userId;
    }
    
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="bank_account", nullable=false, length=255)
    public String getBankAccount() {
        return this.bankAccount;
    }
    
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }




}


