package com.ridematefinder.sql;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Pictures generated by hbm2java
 */
@Entity
@Table(name="pictures"
    ,schema="public"
)
public class Pictures  implements java.io.Serializable {


     private UUID id;
     private String picturePath;
     private Set<Badges> badgeses = new HashSet<Badges>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Car> cars = new HashSet<Car>(0);

    public Pictures() {
    }

	
    public Pictures(UUID id, String picturePath) {
        this.id = id;
        this.picturePath = picturePath;
    }
    public Pictures(UUID id, String picturePath, Set<Badges> badgeses, Set<User> users, Set<Car> cars) {
       this.id = id;
       this.picturePath = picturePath;
       this.badgeses = badgeses;
       this.users = users;
       this.cars = cars;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    
    @Column(name="picture_path", nullable=false, length=511)
    public String getPicturePath() {
        return this.picturePath;
    }
    
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pictures")
    public Set<Badges> getBadgeses() {
        return this.badgeses;
    }
    
    public void setBadgeses(Set<Badges> badgeses) {
        this.badgeses = badgeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pictures")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pictures")
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


