server:
  port: 7777
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/ridematefinder
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  flyway:
    locations: classpath:db/migration
    schemas: public
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://www.googleapis.com
          clientId: "clientId"
          clientSecret: "clientSecret"
